manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: codeandr3w
      url-base:  https://github.com/codeandr3w
  projects:
    - name: zmk-joystick
      remote: codeandr3w
      revision: mousepr-andrew
      import: app/west.yml
  self:
    path: config
